name: Deploy to EC2, install Docker
on:
  push:
    branches:
      - main
      - release*
    paths:
      - 'terraform/**'
      - '.github/workflows/provision-ec2.yaml'
      - 'ansible/playbook.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: terraform
    steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.7.1"
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
        - name: Terraform Init
          id: init
          run: terraform init
        
        - name: Terraform Apply
          id: apply
          run: terraform apply --auto-approve
          
        - name: output instance public ip
          id: public_ip
          run: |
            echo "public_ip=$(terraform output -raw instance_public_ip)" >> "$GITHUB_OUTPUT"
        
